import { Document, Page, Text, StyleSheet, Image } from "@react-pdf/renderer";
import { listFilledCvPdfFields } from "@/lib/cv-pdf-fields";

const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontSize: 10,
    lineHeight: 1.4,
  },
  title: {
    fontSize: 20,
    marginBottom: 10,
    fontWeight: "bold",
    textAlign: "center",
  },
  shortID: {
    fontSize: 14,
    marginBottom: 8,
    textAlign: "center",
    color: "#333",
  },
  photoNote: {
    fontSize: 11,
    marginBottom: 10,
    textAlign: "center",
    color: "#4a2545",
  },
  sectionTitle: {
    fontSize: 13,
    marginTop: 14,
    marginBottom: 6,
    fontWeight: "bold",
    backgroundColor: "#f0f0f0",
    padding: 5,
  },
  label: {
    fontWeight: "bold",
    marginTop: 5,
  },
  value: {
    marginBottom: 6,
  },
  photo: {
    width: 140,
    height: 140,
    marginBottom: 8,
    alignSelf: "center",
  },
});

interface CVPdfProps {
  data: Record<string, string>;
}

export const CVPdf = ({ data }: CVPdfProps) => {
  const sections = listFilledCvPdfFields(data);
  const visibility = data.photoVisibility;
  const visibilityLabel =
    visibility === "blurred"
      ? "Photo setting: Blurred"
      : visibility === "visible"
        ? "Photo setting: Visible"
        : data.photoUrl
          ? "Photo uploaded"
          : "No photo uploaded";

  return (
    <Document>
      <Page size="A4" style={styles.page} wrap>
        <Text style={styles.title}>Finding Keepers - CV</Text>
        <Text style={styles.shortID}>Short ID: {data.shortID}</Text>
        <Text style={styles.photoNote}>{visibilityLabel}</Text>
        {data.photoUrl ? <Image src={data.photoUrl} style={styles.photo} /> : null}
        {!data.photoUrl ? (
          <Text style={styles.photoNote}>No profile photo on file.</Text>
        ) : null}
        {sections.flatMap((section) => [
          <Text key={`${section.title}-title`} style={styles.sectionTitle}>
            {section.title}
          </Text>,
          ...section.rows.flatMap((row) => [
            <Text key={`${section.title}-${row.label}-label`} style={styles.label}>
              {row.label}:
            </Text>,
            <Text key={`${section.title}-${row.label}-value`} style={styles.value}>
              {row.value}
            </Text>,
          ]),
        ])}
        <Text style={{ marginTop: 20, fontSize: 9, color: "#666" }}>
          Full CV record generated by Finding Keepers
        </Text>
      </Page>
    </Document>
  );
};
